### ISSUE TITLE
sed error in step 3

### ISSUE THREAD

**Issue by devnullNZ** [takcluster/takserver-ldap#1]
Command returns an error (Ubuntu 24.04.1 LTS):
sed: -e expression #1, char 20: unknown option to `s'

This will work correctly:

sed -i 's|^include: file:///etc/ldap/schema/nis.ldif|#&\ninclude: file:///etc/ldap/schema/rfc2307bis.ldif|' /usr/share/slapd/slapd.init.ldif

**Comment by 45clouds** [comment]
Thanks for pointing out. Will make a note in README.
